<?php global $url_prefix; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<title>HTTP Request Error</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<style>
<!--
td.error {
border: 1px #FF0000 solid;
}

-->
</style>
</head>

<body>
<table width="100%" border="0" cellspacing="0" cellpadding="10">
  <tr>
    <td valign="middle" align="center" class="error">

<strong>HTTP Request Error</strong>
<br /><br />
<a href="<?php echo $url_prefix; ?>index">Plese, go to index!</a>

	</td>
  </tr>
</table>
</body>
</html>